Services
front-end-by-rimantas/39-grupe-portfolio-personal pull request #36
Opened 2022-07-20 11:51 UTC by sjurate

2022-07-20 12:33 UTC, lzraj requested changes

2022-07-20 12:33 UTC, lzraj commented on css/base/base.css
> +  text-transform: capitalize;
ne visur h2 yra capitalized, tad verta nepakeisti base.css

2022-07-21 05:39 UTC, sjurate commented on css/base/base.css
> +  text-transform: capitalize;
Visur, išskyrus vieną vietą: 5 vietose capitalize, 1 vietoj upper case. "Taupant" kodą, logiška custom padaryti vienoj vietoj, o ne penkiose, mano nuomone.

2022-07-21 07:11 UTC, lzraj approved these changes

2022-07-21 09:13 UTC, Inga-Slamaite approved these changes

2022-07-21 12:30 UTC, Torden11 approved these changes

2022-07-21 12:30 UTC, merged

2022-07-21 12:32 UTC, ugnekiev approved these changes