Hero
front-end-by-rimantas/39-grupe-portfolio-personal pull request #39
Opened 2022-07-21 12:27 UTC by ugnekiev

2022-07-21 12:53 UTC, lzraj submitted a review, later dismissed

2022-07-22 05:59 UTC, sjurate reviewed
Tiek žiūrėjom žiūrėjom, bet dabar man atrodo, kad nuo 992px (Large) vis tik originale yra per visą plotį, o ne col-5 ir col-5 :D kaip kitiems atrodo?

2022-07-22 06:14 UTC, eimazil requested changes
1. Telefono ir kompiuterio rezoliucijose apačioje neturi būti padding, nuotraukia baigiasi kartu su sectionu.
2. Kompiuterio rezoliucijoje h1 tekstas netelpa ir breakinasi per 2 eilutes, orginale išlieka 1 eilutėje.
3. Didžiausioje rezoliucijoje sakyčiau nereikia to margin-left ir ten po 6 stulpelius man atrodo. Tokiu būdu ir tekstas susitvarkytų. 
4. Didžiausioje rezoliucijoje tekstas sulygiuotas viršuje lygiai su nuotrauka.

2022-07-23 10:27 UTC, eimazil requested changes
1. Pavyzdyje fontas keičiasi tik vieną kartą prie 992px, nėra tarpinio 48px dydžio.
2. Pavyzdyje telefono dydyje nuotrauka neužima viso pločio, nepamenu, ką mes ten kalbėjom, ar kad mums taip gražiau gal, kai visą užima.
3. Vidutiniame dydyje nuotrauka ir tekstas turėtų būti sectiono viduryje. Tekstas turėtų būti centruotas nuotraukos atžvilgiu per vidurį.
4. Didžiausiame dydyje tekstas turėtų būti su nuotraukos viršumi.

2022-07-26 06:58 UTC, sjurate reviewed
Manau, kad svarbiausia 
-sutvarkyti nuotraukos dydį small rezoliucijoje 
-large rezoliucijoje  atiduoti visą plotį (pakeisti į col-lg-6 ir nuimti ml-lg-1)

2022-07-27 06:37 UTC, closed without merging