projects static
front-end-by-rimantas/39-grupe-portfolio-personal pull request #40
Opened 2022-07-21 13:25 UTC by lzraj

2022-07-22 05:50 UTC, sjurate requested changes
Uff atrodo, kad daug darbelio buvo :) bet responsive dizaine img'ai atrodo ženkliai sumažėja, labiau nei originaliam projekte. Gal įmanoma pataisyt? Ir nėra tarpo tarp projekto nuotraukos ir jo antrastės (pvz tarp img ir "2D Vinyl Design").

2022-07-22 08:00 UTC, ugnekiev commented
Neblogai padirbėta, tik reiktų padding'ą nuimti nuo .imgbox klasės kai yra kompiuterio ekranas. nes per dideli tarpai, o nnuotraukos per mažos.

2022-07-25 15:44 UTC, sjurate requested changes
dingo 133 eilute layout kode, pagriuvo dizainas < small ekrane

2022-07-25 15:44 UTC, sjurate commented on css/base/layout.css
> -@media (min-width: 576px) {
Dingo šita eilutė, sugriuvo < small dizainas ;/

2022-07-26 07:42 UTC, lzraj reviewed
ačiū už pastabas, pakeitimai padaryti

2022-07-27 05:41 UTC, sjurate commented on css/pages/home.css
> +.projects.img {
Nera tarpo

2022-07-27 05:41 UTC, sjurate commented on css/pages/home.css
> +.projects. img:hover {
taskas po projects, ne pries img

2022-07-27 05:42 UTC, sjurate requested changes
Taskeliai ir tarpeliai ne vietoje, todel susigadino hover dizainas ir nebemazeja img mazinant ekrano dydi

2022-07-28 06:58 UTC, sjurate approved these changes

2022-07-28 06:58 UTC, eimazil approved these changes

2022-07-28 07:00 UTC, Inga-Slamaite approved these changes

2022-07-28 07:00 UTC, ugnekiev approved these changes

2022-07-28 07:00 UTC, merged