Feedback
front-end-by-rimantas/39-grupe-portfolio-personal pull request #43
Opened 2022-07-22 12:20 UTC by Torden11

1) Rodykles buvo paimtos is font awesome.  Kuo panasesniu jame nera. Bandziau kopijuoti panasesniu rodkyliu koda, bet man nepavyko ju sukonstruoti.
2) Tarpas tarp korteliu nesimazina nes  6+6. Jis siek tiek neatitinka  originalo.

2022-07-25 06:32 UTC, sjurate reviewed
Sumažėjus ekrano dydžiui ir rodyklėms "nukritus" apačion, trūktsta apačioj po jom paddingo/margin-bottom.

2022-07-25 06:51 UTC, eimazil requested changes
- [ ] Ten kur vardai man panašiau į h3, ne h4. 
- [ ] Orginale, ten kur rodyklės matosi, kad yra kažkoks pilkas fonas, kuris dar sukuria kaip backgroundą tarp rodyklių.
- [ ] Pačiam section reikia daugiau paddingo ir rodiklytės vidutiniame dydyje turėtų nukristi ne į section apačią, o šiek tiek arčiau feedbackų. 
- [ ] Panašu, kad shadow mygtukų kitos spalvos, labiau pilkas nei violetinis.

2022-07-25 11:13 UTC, Torden11 commented
Changes done. Please review again.

2022-07-25 12:42 UTC, sjurate approved these changes

2022-07-26 12:28 UTC, lzraj approved these changes

2022-07-27 06:51 UTC, eimazil approved these changes

2022-07-27 06:51 UTC, merged